"""add return_date to bookings

Revision ID: 4b0cb8028e68
Revises: cc4f75ca6ba6
Create Date: 2026-09-16 20:32:45.390566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0cb8028e68'
down_revision = 'cc4f75ca6ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('return_date')

    # ### end Alembic commands ###
