"""add pricing_unit to tours

Revision ID: 7c029fec54cd
Revises: 887d24966e59
Create Date: 2026-09-21 10:53:57.287090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c029fec54cd'
down_revision = '887d24966e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_unit', sa.String(), server_default=sa.text("'per_person'"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('pricing_unit')

    # ### end Alembic commands ###
