"""add high season pricing to tours

Revision ID: 887d24966e59
Revises: 4b0cb8028e68
Create Date: 2026-09-21 10:49:47.091421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887d24966e59'
down_revision = '4b0cb8028e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('high_season_price_per_adult', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('high_season_price_per_child', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('high_season_price_per_child')
        batch_op.drop_column('high_season_price_per_adult')

    # ### end Alembic commands ###
