/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminToursRouteImport } from './routes/admin.tours'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerBookingsRouteImport } from './routes/customer.bookings'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerPaymentsRouteImport } from './routes/customer.payments'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerReviewsRouteImport } from './routes/customer.reviews'
import { Route as CustomerSettingsRouteImport } from './routes/customer.settings'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerTripsRouteImport } from './routes/customer.trips'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as ToursTourIdRouteImport } from './routes/tours_.$tourId'
import { Route as CustomerBookingsBookingIdRouteImport } from './routes/customer.bookings_.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerReviewsRoute = CustomerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTripsRoute = CustomerTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => CustomerRoute,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours_/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBookingsBookingIdRoute =
  CustomerBookingsBookingIdRouteImport.update({
    id: '/bookings_/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => CustomerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tours': typeof ToursRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/bookings/$bookingId': typeof CustomerBookingsBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tours': typeof ToursRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/tours/$tourId': typeof ToursTourIdRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/bookings/$bookingId': typeof CustomerBookingsBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tours': typeof ToursRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/reviews': typeof CustomerReviewsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/trips': typeof CustomerTripsRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/tours_/$tourId': typeof ToursTourIdRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/bookings_/$bookingId': typeof CustomerBookingsBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/signin'
    | '/signup'
    | '/tours'
    | '/admin/bookings'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wishlist'
    | '/tours/$tourId'
    | '/admin/'
    | '/customer/'
    | '/customer/bookings/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/tours'
    | '/admin/bookings'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wishlist'
    | '/tours/$tourId'
    | '/admin'
    | '/customer'
    | '/customer/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/signin'
    | '/signup'
    | '/tours'
    | '/admin/bookings'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/tours'
    | '/admin/users'
    | '/customer/bookings'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/profile'
    | '/customer/reviews'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/trips'
    | '/customer/wishlist'
    | '/tours_/$tourId'
    | '/admin/'
    | '/customer/'
    | '/customer/bookings_/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ToursRoute: typeof ToursRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments': {
      id: '/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/reviews': {
      id: '/customer/reviews'
      path: '/reviews'
      fullPath: '/customer/reviews'
      preLoaderRoute: typeof CustomerReviewsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/trips': {
      id: '/customer/trips'
      path: '/trips'
      fullPath: '/customer/trips'
      preLoaderRoute: typeof CustomerTripsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/tours_/$tourId': {
      id: '/tours_/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/bookings_/$bookingId': {
      id: '/customer/bookings_/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/customer/bookings/$bookingId'
      preLoaderRoute: typeof CustomerBookingsBookingIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminToursRoute: AdminToursRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerReviewsRoute: typeof CustomerReviewsRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerTripsRoute: typeof CustomerTripsRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerBookingsBookingIdRoute: typeof CustomerBookingsBookingIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerPaymentsRoute: CustomerPaymentsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerReviewsRoute: CustomerReviewsRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerTripsRoute: CustomerTripsRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerBookingsBookingIdRoute: CustomerBookingsBookingIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ToursRoute: ToursRoute,
  ToursTourIdRoute: ToursTourIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
